export const ext2Lang = {
  adb: 'ada',
  awk: 'awk',
  bash: 'sh',
  c: 'c',
  cc: 'cpp',
  csharp: 'csharp',
  cpp: 'cpp',
  f95: 'f90',
  hs: 'haskell',
  java: 'java',
  js: 'javascript',
  kt: 'kt',
  lua: 'lua',
  pas: 'pascal',
  pl: 'perl',
  plg: 'prolog',
  py: 'python',
  py2: 'python',
  py3: 'python',
  r: 'r',
  rb: 'ruby',
  scala: 'scala',
  swift: 'swift',
  txt: 'txt',
};

export const Languages = {
  ada: 'Ada',
  awk: 'AWK',
  bash: 'Bash Shell',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  f90: 'Fortran 90',
  haskell: 'Haskell',
  java: 'Java',
  javascript: 'JavaScript',
  kt: 'Kotlin',
  lua: 'Lua',
  pascal: 'Pascal',
  perl: 'Perl',
  prolog: 'Prolog',
  python: 'Python',
  r: 'R',
  ruby: 'Ruby',
  scala: 'Scala',
  swift: 'Swift',
  txt: 'Plain Text',
};
