export const HTML_COLORS = {
    black: '#000000',
    silver: '#C0C0C0',
    gray: '#808080',
    white: '#FFFFFF',
    maroon: '#800000',
    red: '#FF0000',
    purple: '#800080',
    fuchsia: '#FF00FF',
    green: '#008000',
    lime: '#00FF00',
    olive: '#808000',
    yellow: '#FFFF00',
    navy: '#000080',
    blue: '#0000FF',
    teal: '#008080',
    aliceblue: '#f0f8ff',
    antiquewhite: '#faebd7',
    aquamarine: '#7fffd4',
    azure: '#f0ffff',
    beige: '#f5f5dc',
    bisque: '#ffe4c4',
    blanchedalmond: '#ffebcd',
    blueviolet: '#8a2be2',
    brown: '#a52a2a',
    burlywood: '#deb887',
    cadetblue: '#5f9ea0',
    chartreuse: '#7fff00',
    chocolate: '#d2691e',
    coral: '#ff7f50',
    cornflowerblue: '#6495ed',
    cornsilk: '#fff8dc',
    crimson: '#dc143c',
    cyan: '#00ffff',
    darkblue: '#00008b',
    darkcyan: '#008b8b',
    darkgoldenrod: '#b8860b',
    darkgray: '#a9a9a9',
    darkgreen: '#006400',
    darkkhaki: '#bdb76b',
    darkmagenta: '#8b008b',
    darkolivegreen: '#556b2f',
    darkorange: '#ff8c00',
    darkorchid: '#9932cc',
    darkred: '#8b0000',
    darksalmon: '#e9967a',
    darkseagreen: '#8fbc8f',
    darkslateblue: '#483d8b',
    darkslategray: '#2f4f4f',
    darkturquoise: '#00ced1',
    darkviolet: '#9400d3',
    deeppink: '#ff1493',
    deepskyblue: '#00bfff',
    dimgray: '#696969',
    dodgerblue: '#1e90ff',
    firebrick: '#b22222',
    floralwhite: '#fffaf0',
    forestgreen: '#228b22',
    gainsboro: '#dcdcdc',
    ghostwhite: '#f8f8ff',
    gold: '#ffd700',
    goldenrod: '#daa520',
    greenyellow: '#adff2f',
    honeydew: '#f0fff0',
    hotpink: '#ff69b4',
    indianred: '#cd5c5c',
    indigo: '#4b0082',
    ivory: '#fffff0',
    khaki: '#f0e68c',
    lavender: '#e6e6fa',
    lavenderblush: '#fff0f5',
    lawngreen: '#7cfc00',
    lemonchiffon: '#fffacd',
    lightblue: '#add8e6',
    lightcoral: '#f08080',
    lightcyan: '#e0ffff',
    lightgoldenrodyellow: '#fafad2',
    lightgray: '#d3d3d3',
    lightgreen: '#90ee90',
    lightpink: '#ffb6c1',
    lightsalmon: '#ffa07a',
    lightseagreen: '#20b2aa',
    lightskyblue: '#87cefa',
    lightslategray: '#778899',
    lightsteelblue: '#b0c4de',
    lightyellow: '#ffffe0',
    limegreen: '#32cd32',
    linen: '#faf0e6',
    magenta: '#ff00ff',
    mediumaquamarine: '#66cdaa',
    mediumblue: '#0000cd',
    mediumorchid: '#ba55d3',
    mediumpurple: '#9370db',
    mediumseagreen: '#3cb371',
    mediumslateblue: '#7b68ee',
    mediumspringgreen: '#00fa9a',
    mediumturquoise: '#48d1cc',
    mediumvioletred: '#c71585',
    midnightblue: '#191970',
    mintcream: '#f5fffa',
    mistyrose: '#ffe4e1',
    moccasin: '#ffe4b5',
    navajowhite: '#ffdead',
    oldlace: '#fdf5e6',
    olivedrab: '#6b8e23',
    orange: '#ffa500',
    orangered: '#ff4500',
    orchid: '#da70d6',
    palegoldenrod: '#eee8aa',
    palegreen: '#98fb98',
    paleturquoise: '#afeeee',
    palevioletred: '#db7093',
    papayawhip: '#ffefd5',
    peachpuff: '#ffdab9',
    peru: '#cd853f',
    pink: '#ffc0cb',
    plum: '#dda0dd',
    powderblue: '#b0e0e6',
    rosybrown: '#bc8f8f',
    royalblue: '#4169e1',
    saddlebrown: '#8b4513',
    salmon: '#fa8072',
    sandybrown: '#f4a460',
    seagreen: '#2e8b57',
    seashell: '#fff5ee',
    sienna: '#a0522d',
    skyblue: '#87ceeb',
    slateblue: '#6a5acd',
    slategray: '#708090',
    snow: '#fffafa',
    springgreen: '#00ff7f',
    steelblue: '#4682b4',
    tan: '#d2b48c',
    thistle: '#d8bfd8',
    tomato: '#ff6347',
    turquoise: '#40e0d0',
    violet: '#ee82ee',
    wheat: '#f5deb3',
    whitesmoke: '#f5f5f5',
    yellowgreen: '#9acd32',
};

export const CHINESE_NAME = {
    aliceblue: '艾利斯兰',
    antiquewhite: '古董白',
    aquamarine: '蓝晶色',
    azure: '天蓝色',
    beige: '米色',
    bisque: '桔黄色',
    black: '黑色',
    blanchedalmond: '白杏色',
    blue: '蓝色',
    blueviolet: '紫罗兰色',
    brown: '棕色',
    burlywood: '实木色',
    cadetblue: '军蓝色',
    chartreuse: '黄绿色',
    chocolate: '巧克力色',
    coral: '珊瑚色',
    cornflowerblue: '矢车菊蓝',
    cornsilk: '玉米丝色',
    crimson: '绯红',
    cyan: '青色',
    darkblue: '深蓝色',
    darkcyan: '深青色',
    darkgoldenrod: '深金黄色',
    darkgray: '深灰色',
    darkgreen: '深绿色',
    darkkhaki: '深卡其色',
    darkmagenta: '深紫红色',
    darkolivegreen: '深橄榄绿',
    darkorange: '深橙色',
    darkorchid: '深兰花紫',
    darkred: '深红色',
    darksalmon: '深橙红',
    darkseagreen: '深海绿',
    darkslateblue: '深板岩蓝',
    darkslategray: '深板岩灰',
    darkturquoise: '深宝石绿',
    darkviolet: '深紫罗兰',
    deeppink: '深粉红',
    deepskyblue: '深天蓝',
    dimgray: '暗灰色',
    dodgerblue: '道奇蓝',
    firebrick: '火砖色',
    floralwhite: '花白色',
    forestgreen: '森林绿',
    fuchsia: '紫红色',
    gainsboro: '亮灰色',
    ghostwhite: '幽灵白',
    gold: '金色',
    goldenrod: '金菊黄',
    gray: '灰色',
    green: '绿色',
    greenyellow: '绿黄色',
    honeydew: '蜜瓜色',
    hotpink: '亮粉红',
    indianred: '印度红',
    indigo: '靛青色',
    ivory: '象牙色',
    khaki: '卡其色',
    lavender: '薰衣草色',
    lavenderblush: '淡紫红',
    lawngreen: '草绿色',
    lemonchiffon: '柠檬绸色',
    lightblue: '淡蓝',
    lightcoral: '浅珊瑚色',
    lightcyan: '浅青',
    lightgoldenrodyellow: '浅金黄色',
    lightgray: '浅灰',
    lightgreen: '浅绿',
    lightpink: '浅粉',
    lightsalmon: '浅橙红',
    lightseagreen: '浅海绿',
    lightskyblue: '浅天蓝',
    lightslategray: '浅板岩灰',
    lightsteelblue: '浅钢蓝',
    lightyellow: '浅黄',
    lime: '酸橙绿',
    limegreen: '酸橙绿',
    linen: '亚麻色',
    magenta: '洋红',
    maroon: '栗色',
    mediumaquamarine: '中碧绿',
    mediumblue: '中蓝色',
    mediumorchid: '中兰花紫',
    mediumpurple: '中紫色',
    mediumseagreen: '中海绿',
    mediumslateblue: '中板岩蓝',
    mediumspringgreen: '中春绿',
    mediumturquoise: '中宝石绿',
    mediumvioletred: '中紫罗兰',
    midnightblue: '午夜蓝',
    mintcream: '薄荷乳白',
    mistyrose: '薄雾玫瑰',
    moccasin: '鹿皮色',
    navajowhite: '纳瓦白',
    navy: '海军蓝',
    oldlace: '老花色',
    olive: '橄榄色',
    olivedrab: '橄榄绿',
    orange: '橙色',
    orangered: '橙红色',
    orchid: '兰花紫',
    palegoldenrod: '灰菊黄',
    palegreen: '灰绿色',
    paleturquoise: '灰宝石绿',
    palevioletred: '灰紫罗兰',
    papayawhip: '番木色',
    peachpuff: '桃色',
    peru: '秘鲁色',
    pink: '粉红色',
    plum: '洋李色',
    powderblue: '粉蓝色',
    purple: '紫色',
    red: '红色',
    rosybrown: '玫瑰褐',
    royalblue: '皇家蓝',
    saddlebrown: '马鞍棕色',
    salmon: '鲜肉色',
    sandybrown: '沙棕色',
    seagreen: '海绿色',
    seashell: '贝壳白',
    sienna: '赭色',
    silver: '银色',
    skyblue: '天蓝色',
    slateblue: '板岩蓝',
    slategray: '板岩灰',
    snow: '雪白色',
    springgreen: '春绿色',
    steelblue: '钢蓝色',
    tan: '茶色',
    teal: '水鸭色',
    thistle: '蓟色',
    tomato: '番茄红',
    turquoise: '宝石绿',
    violet: '紫罗兰',
    wheat: '小麦色',
    white: '白色',
    whitesmoke: '烟白色',
    yellow: '黄色',
    yellowgreen: '黄绿色',
};

export function convertToColor(hex) {
    if (!hex.match(/^#[0-9a-fA-F]{3,6}$/)) {
        return hex;
    }

    // Expand short 3 digit hex version
    if (hex.match(/^#[0-9a-fA-F]{3}$/)) {
        hex = `#${hex.slice(1).split('').map((c) => c + c).join('')}`;
    }

    if (!hex.match(/^#[0-9a-fA-F]{6}$/)) {
        return null;
    }

    let bestMatch = 'unknown';
    let bestDistance = 999999;

    for (const [name, color] of Object.entries(HTML_COLORS)) {
        const distance = [1, 3, 5].map((i) => Math.abs(
            parseInt(hex.slice(i, i + 2), 16) - parseInt(color.slice(i, i + 2), 16))).reduce((a, b) => a + b, 0);
        if (distance < bestDistance) {
            bestMatch = name;
            bestDistance = distance;
        }
    }

    return bestMatch;
}

export const convertToChinese = (color) => CHINESE_NAME[color] || color;

export const getBalloonName = (color = '', lang = '') => {
    if (!color.startsWith('#')) return lang === 'zh' ? convertToChinese(color) : color;
    const c = convertToColor(color);
    return lang === 'zh' ? convertToChinese(c) : c;
};
