export const HTML_COLORS = {
    black: '#000000',
    silver: '#C0C0C0',
    gray: '#808080',
    white: '#FFFFFF',
    maroon: '#800000',
    red: '#FF0000',
    purple: '#800080',
    fuchsia: '#FF00FF',
    green: '#008000',
    lime: '#00FF00',
    olive: '#808000',
    yellow: '#FFFF00',
    navy: '#000080',
    blue: '#0000FF',
    teal: '#008080',
    aqua: '#00FFFF',
    aliceblue: '#f0f8ff',
    antiquewhite: '#faebd7',
    aquamarine: '#7fffd4',
    azure: '#f0ffff',
    beige: '#f5f5dc',
    bisque: '#ffe4c4',
    blanchedalmond: '#ffebcd',
    blueviolet: '#8a2be2',
    brown: '#a52a2a',
    burlywood: '#deb887',
    cadetblue: '#5f9ea0',
    chartreuse: '#7fff00',
    chocolate: '#d2691e',
    coral: '#ff7f50',
    cornflowerblue: '#6495ed',
    cornsilk: '#fff8dc',
    crimson: '#dc143c',
    cyan: '#00ffff',
    darkblue: '#00008b',
    darkcyan: '#008b8b',
    darkgoldenrod: '#b8860b',
    darkgray: '#a9a9a9',
    darkgreen: '#006400',
    darkgrey: '#a9a9a9',
    darkkhaki: '#bdb76b',
    darkmagenta: '#8b008b',
    darkolivegreen: '#556b2f',
    darkorange: '#ff8c00',
    darkorchid: '#9932cc',
    darkred: '#8b0000',
    darksalmon: '#e9967a',
    darkseagreen: '#8fbc8f',
    darkslateblue: '#483d8b',
    darkslategray: '#2f4f4f',
    darkslategrey: '#2f4f4f',
    darkturquoise: '#00ced1',
    darkviolet: '#9400d3',
    deeppink: '#ff1493',
    deepskyblue: '#00bfff',
    dimgray: '#696969',
    dimgrey: '#696969',
    dodgerblue: '#1e90ff',
    firebrick: '#b22222',
    floralwhite: '#fffaf0',
    forestgreen: '#228b22',
    gainsboro: '#dcdcdc',
    ghostwhite: '#f8f8ff',
    gold: '#ffd700',
    goldenrod: '#daa520',
    greenyellow: '#adff2f',
    grey: '#808080',
    honeydew: '#f0fff0',
    hotpink: '#ff69b4',
    indianred: '#cd5c5c',
    indigo: '#4b0082',
    ivory: '#fffff0',
    khaki: '#f0e68c',
    lavender: '#e6e6fa',
    lavenderblush: '#fff0f5',
    lawngreen: '#7cfc00',
    lemonchiffon: '#fffacd',
    lightblue: '#add8e6',
    lightcoral: '#f08080',
    lightcyan: '#e0ffff',
    lightgoldenrodyellow: '#fafad2',
    lightgray: '#d3d3d3',
    lightgreen: '#90ee90',
    lightgrey: '#d3d3d3',
    lightpink: '#ffb6c1',
    lightsalmon: '#ffa07a',
    lightseagreen: '#20b2aa',
    lightskyblue: '#87cefa',
    lightslategray: '#778899',
    lightslategrey: '#778899',
    lightsteelblue: '#b0c4de',
    lightyellow: '#ffffe0',
    limegreen: '#32cd32',
    linen: '#faf0e6',
    magenta: '#ff00ff',
    mediumaquamarine: '#66cdaa',
    mediumblue: '#0000cd',
    mediumorchid: '#ba55d3',
    mediumpurple: '#9370db',
    mediumseagreen: '#3cb371',
    mediumslateblue: '#7b68ee',
    mediumspringgreen: '#00fa9a',
    mediumturquoise: '#48d1cc',
    mediumvioletred: '#c71585',
    midnightblue: '#191970',
    mintcream: '#f5fffa',
    mistyrose: '#ffe4e1',
    moccasin: '#ffe4b5',
    navajowhite: '#ffdead',
    oldlace: '#fdf5e6',
    olivedrab: '#6b8e23',
    orange: '#ffa500',
    orangered: '#ff4500',
    orchid: '#da70d6',
    palegoldenrod: '#eee8aa',
    palegreen: '#98fb98',
    paleturquoise: '#afeeee',
    palevioletred: '#db7093',
    papayawhip: '#ffefd5',
    peachpuff: '#ffdab9',
    peru: '#cd853f',
    pink: '#ffc0cb',
    plum: '#dda0dd',
    powderblue: '#b0e0e6',
    rosybrown: '#bc8f8f',
    royalblue: '#4169e1',
    saddlebrown: '#8b4513',
    salmon: '#fa8072',
    sandybrown: '#f4a460',
    seagreen: '#2e8b57',
    seashell: '#fff5ee',
    sienna: '#a0522d',
    skyblue: '#87ceeb',
    slateblue: '#6a5acd',
    slategray: '#708090',
    slategrey: '#708090',
    snow: '#fffafa',
    springgreen: '#00ff7f',
    steelblue: '#4682b4',
    tan: '#d2b48c',
    thistle: '#d8bfd8',
    tomato: '#ff6347',
    turquoise: '#40e0d0',
    violet: '#ee82ee',
    wheat: '#f5deb3',
    whitesmoke: '#f5f5f5',
    yellowgreen: '#9acd32',
};

export const CHINESE_NAME = {
    aliceblue: '艾利斯兰',
    antiquewhite: '古董白',
    aqua: '浅绿色',
    aquamarine: '碧绿色',
    azure: '天蓝色',
    beige: '米色',
    bisque: '桔黄色',
    black: '黑色',
    blanchedalmond: '白杏色',
    blue: '蓝色',
    blueviolet: '紫罗兰色',
    brown: '褐色',
    burlywood: '实木色',
    cadetblue: '军兰色',
    chartreuse: '黄绿色',
    chocolate: '巧可力色',
    coral: '珊瑚色',
    cornflowerblue: '菊兰色',
    cornsilk: '米绸色',
    crimson: '暗深红色',
    cyan: '青色',
    darkblue: '暗蓝色',
    darkcyan: '暗青色',
    darkgoldenrod: '暗金黄色',
    darkgray: '暗灰色',
    darkgreen: '暗绿色',
    darkgrey: '暗灰色',
    darkkhaki: '暗黄褐色',
    darkmagenta: '暗洋红',
    darkolivegreen: '暗橄榄绿',
    darkorange: '暗桔黄色',
    darkorchid: '暗紫色',
    darkred: '暗红色',
    darksalmon: '暗肉色',
    darkseagreen: '暗海兰色',
    darkslateblue: '暗灰蓝色',
    darkslategray: '暗瓦灰色',
    darkslategrey: '暗瓦灰色',
    darkturquoise: '暗宝石绿',
    darkviolet: '暗紫罗兰色',
    deeppink: '深粉红色',
    deepskyblue: '深天蓝色',
    dimgray: '暗灰色',
    dimgrey: '暗灰色',
    dodgerblue: '闪兰色',
    firebrick: '火砖色',
    floralwhite: '花白色',
    forestgreen: '森林绿',
    fuchsia: '紫红色',
    gainsboro: '淡灰色',
    ghostwhite: '幽灵白',
    gold: '金色',
    goldenrod: '金麒麟色',
    gray: '灰色',
    green: '绿色',
    greenyellow: '黄绿色',
    grey: '灰色',
    honeydew: '蜜色',
    hotpink: '热粉红色',
    indianred: '印第安红',
    indigo: '靛青色',
    ivory: '象牙色',
    khaki: '黄褐色',
    lavender: '淡紫色',
    lavenderblush: '淡紫红',
    lawngreen: '草绿色',
    lemonchiffon: '柠檬绸色',
    lightblue: '亮蓝色',
    lightcoral: '亮珊瑚色',
    lightcyan: '亮青色',
    lightgoldenrodyellow: '亮金黄色',
    lightgray: '亮灰色',
    lightgreen: '亮绿色',
    lightgrey: '亮灰色',
    lightpink: '亮粉红色',
    lightsalmon: '亮肉色',
    lightseagreen: '亮海蓝色',
    lightskyblue: '亮天蓝色',
    lightslategray: '亮蓝灰',
    lightslategrey: '亮蓝灰',
    lightsteelblue: '亮钢兰色',
    lightyellow: '亮黄色',
    lime: '酸橙色',
    limegreen: '橙绿色',
    linen: '亚麻色',
    magenta: '红紫色',
    maroon: '粟色',
    mediumaquamarine: '中绿色',
    mediumblue: '中兰色',
    mediumorchid: '中粉紫色',
    mediumpurple: '中紫色',
    mediumseagreen: '中海蓝',
    mediumslateblue: '中暗蓝色',
    mediumspringgreen: '中春绿色',
    mediumturquoise: '中绿宝石',
    mediumvioletred: '中紫罗兰色',
    midnightblue: '中灰兰色',
    mintcream: '薄荷色',
    mistyrose: '浅玫瑰色',
    moccasin: '鹿皮色',
    navajowhite: '纳瓦白',
    navy: '海军色',
    oldlace: '老花色',
    olive: '橄榄色',
    olivedrab: '深绿褐色',
    orange: '橙色',
    orangered: '红橙色',
    orchid: '淡紫色',
    palegoldenrod: '苍麒麟色',
    palegreen: '苍绿色',
    paleturquoise: '苍宝石绿',
    palevioletred: '苍紫罗兰色',
    papayawhip: '番木色',
    peachpuff: '桃色',
    peru: '秘鲁色',
    pink: '粉红色',
    plum: '洋李色',
    powderblue: '粉蓝色',
    purple: '紫色',
    red: '红色',
    rosybrown: '褐玫瑰红',
    royalblue: '皇家蓝',
    saddlebrown: '重褐色',
    salmon: '鲜肉色',
    sandybrown: '沙褐色',
    seagreen: '海绿色',
    seashell: '海贝色',
    sienna: '赭色',
    silver: '银色',
    skyblue: '天蓝色',
    slateblue: '石蓝色',
    slategray: '灰石色',
    slategrey: '灰石色',
    snow: '雪白色',
    springgreen: '春绿色',
    steelblue: '钢兰色',
    tan: '茶色',
    teal: '水鸭色',
    thistle: '蓟色',
    tomato: '西红柿色',
    turquoise: '青绿色',
    violet: '紫罗兰色',
    wheat: '浅黄色',
    white: '白色',
    whitesmoke: '烟白色',
    yellow: '黄色',
    yellowgreen: '黄绿色',
};

export function convertToColor(hex) {
    if (!hex.match(/^#[0-9a-fA-F]{3,6}$/)) {
        return hex;
    }

    // Expand short 3 digit hex version
    if (hex.match(/^#[0-9a-fA-F]{3}$/)) {
        hex = `#${hex.slice(1).split('').map((c) => c + c).join('')}`;
    }

    if (!hex.match(/^#[0-9a-fA-F]{6}$/)) {
        return null;
    }

    let bestMatch = 'unknown';
    let bestDistance = 999999;

    for (const [name, color] of Object.entries(HTML_COLORS)) {
        const distance = [1, 3, 5].map((i) => Math.abs(
            parseInt(hex.slice(i, i + 2), 16) - parseInt(color.slice(i, i + 2), 16))).reduce((a, b) => a + b, 0);
        if (distance < bestDistance) {
            bestMatch = name;
            bestDistance = distance;
        }
    }

    return bestMatch;
}

export function convertToChinese(color) {
    return CHINESE_NAME[color] || color;
}
