#!/bin/sh

UPTIME="$(cut -d. -f1 /proc/uptime)"
# get machine mac address
NETDEV=$(ip route show default | awk '/default/ {print $5}' | head -n 1)
test -n "$NETDEV" && MACADDR="$(tr -d : < "/sys/class/net/$NETDEV/address")"
test -z "$MACADDR" && MACADDR="00:00:00:00:00:00"

test -z "$OS" && OS="$(cat /etc/issue.net | awk '{print $1}')"
test -z "$OS" && OS="$(cat /etc/issue | awk '{print $1}')"
test -z "$OS" && OS="$(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | sed 's/"//g')"
test -z "$OS" && OS="$(cat /etc/os-release | grep NAME | cut -d= -f2 | sed 's/"//g')"
test -z "$OS" && OS="unknown"

test -r /etc/icpcimage-version && VERSION="$(cat /etc/icpcimage-version)"
test -z "$VERSION" && VERSION="$(grep -Po "version=\K\S*" /proc/cmdline)"
test -z "$VERSION" && VERSION="devel"

# get machine kernel version
KERNEL="$(uname -r)"

test -r /etc/hostname && SEATS="$(cat /etc/hostname)"

test -r /proc/cpuinfo && CPU="$(cat /proc/cpuinfo | grep 'model name' | uniq | awk -F: '{print $2}' | sed 's/^[ \t]*//g')"
test -r /proc/cpuinfo && CPU="$(grep -c processor /proc/cpuinfo) x $CPU"
test -z "$CPU" && CPU="unknown"
# replace spaces with underscores
CPU="$(echo $CPU | sed 's/ /_/g')"

# get machine cpu used percentage
CPUUSED="$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}')"

# get machine load average
LOAD="$(cat /proc/loadavg | awk '{print $1" "$2" "$3}')"

# get machine memory total
MEM="$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')"
MemFree="$(cat /proc/meminfo | grep MemFree | awk '{print $2}')"
MEMUSED="$(($MEM-$MemFree))"

if [ ! -f /root/exec-result ]; then
  touch /root/exec-result
fi

curl -s $HEARTBEATURL -X POST \
  -F "file=@/root/exec-result" \
  -d "mac=$MACADDR" \
  -d "version=$VERSION" \
  -d "uptime=$UPTIME" \
  -d "seats=$SEATS" \
  -d "os=$OS" \
  -d "kernel=$KERNEL" \
  -d "cpu=$CPU" \
  -d "cpuused=$CPUUSED" \
  -d "mem=$MEM" \
  -d "memused=$MEMUSED" \
  -d "load=$LOAD" \
  -o /root/heartbeat-exec.sh

if [ -f /root/heartbeat-exec.sh ]; then
  head /root/heartbeat-exec.sh | grep '#!/bin/bash' && bash /root/heartbeat-exec.sh >/root/exec-result 2>&1 || true
fi
